ACRONYM_MAP = {

"A&P": "Airframe and Powerplant (mechanic). A certified technician qualified to inspect, maintain, and repair aircraft airframes and engines.",
"A/C": "Aircraft.",
"A/R": "Airworthiness Review. A periodic review of an aircraft's records and physical condition to ensure it meets regulatory requirements.",
"AAA": "Airport Authorities Association.",
"AAR": "Airport Acceptance Rate. The number of aircraft an airport can handle per hour under specific conditions.",
"AAS": "Airport Advisory Service",
"AAV": "Autonomous Aerial Vehicle.",
"AB": "Afterburner (on a jet engine).",
"AC": "Advisory Circular. FAA publications providing guidance and recommendations on various aviation topics. Also, alternating current.",
"ACARS": "Aircraft Communications Addressing and Reporting System. A digital datalink systemfor transmitting short messages between aircraft and ground stations.",
"ACC": "Area Control Center. A facility responsible for controlling IFR traffic within a specificairspace.",
"ACMI": "Aircraft, Crew, Maintenance, and Insurance. A type of aircraft leasing agreement where the lessor provides all four elements.",
"AD": "Airworthiness Directive. A mandatory notification issued by the FAA requiring correction of an unsafe condition found in an aircraft, engine, propeller, or appliance.",
"ADA": "Americans with Disabilities Act.",
"ADF": "Automatic Direction Finder. A radio navigation instrument that points to a non-directional beacon (NDB).",
"ADI": "Attitude Direction Indicator.",
"ADIZ": "Air Defense Identification Zone. Airspace over land or water where identification of aircraft is required in the interest of national security.",
"ADS-B": "Automatic Dependent Surveillance-Broadcast. A surveillance technology where an aircraft broadcasts its position, altitude, and other data derived from onboard systems for use by air traffic control and other aircraft.",
"AFM": "Aircraft Flight Manual. The official document containing operating procedures and limitations for a specific aircraft type.",
"AFR": "Accident Frequency Rate.",
"AGL": "Above Ground Level. The altitude of an aircraft above the terrain directly beneath it.",
"AIC": "Aeronautical Information Circular.",
"AIM": "Aeronautical Information Manual. A comprehensive guide to basic flight information and ATC procedures.",
"AIRMET": "Airman's Meteorological Information. A weather advisory concerning moderate icing, moderate turbulence, sustained winds of 30 knots or more, and/or widespread areas of ceilings less than 1,000 feet and/or visibility less than 3 miles.",
"ALS": "Approach Lighting System.",
"AMM": "Aircraft Maintenance Manual. A document describing maintenance procedures and schedules for a specific aircraft type.",
"AMOS": "Airline Maintenance and Operations System. Software system used by airlines to manage maintenance and operational data.", 
"AMOC": "Alternative Method of Compliance. An FAA-approved method of complying with an Airworthiness Directive that differs from the method specified in the AD.", 
"AOG": "Aircraft on Ground. A situation where an aircraft is unable to fly due to a maintenance issue.", 
"AOPA": "Aircraft Owners and Pilots Association.", 
"AP": "Autopilot.", 
"APU": "Auxiliary Power Unit. A small engine on an aircraft that provides power for starting the main engines and operating onboard systems while on the ground.", 
"AR": "As Removed. The condition of a component when it is removed from the aircraft.", 
"ARFF": "Aircraft Rescue and Fire Fighting.", 
"ARP": "Airport Reference Point.", 
"ASAP": "Aviation Safety Action Program. A voluntary, non-punitive reporting system that encourages employees to report safety concerns.", 
"ASI": "Airspeed Indicator.", 
"ASL": "Above Sea Level.", 
"ATA": "Air Transport Association. A standardized system for numbering aircraft systems and components, used in maintenance manuals.", 
"ATC": "Air Traffic Control.", 
"ATIS": "Automatic Terminal Information Service. A continuous broadcast of recorded aeronautical information in busy terminal areas.", 
"ATLB": "Air Transport Licensing Board.",
"ATM": "Air Traffic Management.", 
"ATO": "Air Traffic Organization (part of the FAA).", 
"ATPL": "Airline Transport Pilot License. The highest level of pilot certificate.", 
"AVGAS": "Aviation Gasoline. Fuel specifically designed for piston-engine aircraft.",
"BA": "Brake Action. A report of braking performance on a runway due to contaminants like snow or ice.",
"BER": "Beyond Economical Repair. A component that is too expensive to repair and should be replaced.",
"BFO": "Beat Frequency Oscillator. Used in radio receivers.",
"BITE": "Built-In Test Equipment. Self-diagnostic tools within aircraft systems.",
"BLE": "Blended Learning Environment.",
"BOM": "Bill of Materials. A comprehensive list of raw materials, components, and assemblies required to manufacture a product (e.g., an aircraft engine).",
"Borescope Inspection": "Using a flexible scope to inspect engine components without disassembly.",
"BTO": "Build-to-Order. Manufacturing process where aircraft are produced according to specific customer requirements.",
"CAA": "Civil Aviation Authority. The national aviation regulatory authority in many countries (e.g., UK).",
"CAAP": "Civil Aviation Authority of the Philippines.",
"CAAS": "Civil Aviation Authority of Singapore.",
"Capex": "Capital Expenditure. Investments in fixed assets like aircraft.",
"CAS": "Calibrated Airspeed. Indicated airspeed corrected for instrument and position error.",
"CAT": "Clear Air Turbulence.",
"CDA": "Continuous Descent Approach.",
"CDI": "Course Deviation Indicator.",
"CDR": "Conditional Route.",
"CFM": "CFM International. A joint venture between Safran Aircraft Engines (France) and GE Aerospace (US) that produces aircraft engines (e.g., CFM56, LEAP).",
"CG": "Center of Gravity.",
"Chattel Mortgage": "A loan secured by an aircraft.",
"CIM": "Computer Integrated Manufacturing.",
"CIP": "Cleaning In Place.",
"CM": "Condition Monitored. A maintenance philosophy where the condition of components is continuously or periodically monitored using sensors or other methods, and maintenance is performed based on the data collected. Trend Monitoring. No fixed life but are subject to trend monitoring.",
"CMOS": "Complementary Metal-Oxide Semiconductor.",
"CMS": "Configuration Management System.",
"CN": "Certification Notice.",
"CND": "Condition Noted During. Term used in maintenance records.",
"COA": "Certificate of Airworthiness.",
"COM": "Communications (radio).",
"Component": "A self-contained part, combination of parts, subassemblies, or units, which perform a specific function.",
"Consumable": "Items used during maintenance that are not permanently installed in the aircraft (e.g., lubricants, cleaning fluids, safety wire).",
"Corrective Maintenance": "Maintenance performed to restore a system to a functional state after a failure.",
"CPCP": "Corrosion Prevention and Control Program.",
"CPDLC": "Controller Pilot Data Link Communications ",
"CRM": "Crew Resource Management. Training programs focused on improving communication and decision-making in the cockpit.",
"CSN": "Cycles Since New. The total number of cycles a component has completed since it was manufactured. A cycle typically refers to a take-off and landing for aircraft components.",
"CSI": "Cycles Since Installation. The number of cycles a component has completed since it was last installed on an aircraft.",
"CSO": "Cycles Since Overhaul. The number of cycles a component has completed since it was last overhauled.",
"CSU": "Constant Speed Unit.",
"CVR": "Cockpit Voice Recorder.",
"CWT": "Center Wing Tank.",
"DA/H": "Decision Altitude/Height. The altitude or height at which a pilot must decide whether to continue an instrument approach or execute a missed approach.",
"DAR": "Designated Airworthiness Representative. An individual authorized by the FAA to perform airworthiness inspections and issue airworthiness certificates.",
"Deferral": "Postponing maintenance on a non-essential item according to the MEL (Minimum Equipment List).",
"Depreciation": "The reduction in value of an aircraft over time.",
"DGAC": "Direction Générale de l'Aviation Civile (French Civil Aviation Authority).",
"DGCA": "Directorate General of Civil Aviation (Indian Civil Aviation Authority).",
"DME": "Distance Measuring Equipment. A radio navigation aid that provides distance to a ground station.",
"DOA": "Design Organization Approval.",
"DOT": "Department of Transportation.",
"DR": "Dead Reckoning.",
"Dry Lease": "Aircraft lease without crew, maintenance, or insurance.",
"DTG": "Distance To Go.",
"DTS": "Data Transfer System.",
"Dye Penetrant Inspection (PT)": "Uses a dye to reveal surface cracks.",
"EASA": "European Union Aviation Safety Agency. The aviation regulatory authority for the European Union.",
"EASA Form 1": "An authorized release certificate that accompanies aircraft components after maintenance, overhaul, or repair, certifying that the work was performed to approved standards. Equivalent FAA Form 8130-3.",
"EBITDA": "Earnings Before Interest, Taxes, Depreciation, and Amortization. A measure of a company's financial performance.",
"ECAM": "Electronic Centralized Aircraft Monitoring. A system used to display aircraft system information and provide alerts to the crew.", 
"ECU": "Electronic Control Unit.",
"Eddy Current Testing (ET)": "Uses electromagnetic induction to detect surface and near-surface flaws.",
"EFB": "Electronic Flight Bag. A digital replacement for paper charts and flight manuals.",
"EFIS": "Electronic Flight Instrument System. A glass cockpit display system that replaces traditional analog instruments.",
"EGT": "Exhaust Gas Temperature.",
"EICAS": "Engine Indication and Crew Alerting System.",
"ELT": "Emergency Locator Transmitter. A device that automatically transmits a distress signal in the event of an accident.",
"EMC": "Electromagnetic Compatibility.",
"EMI": "Electromagnetic Interference.",
"EOAT": "End of Arm Tooling.",
"EOD": "Explosive Ordnance Disposal.",
"EOP": "Emergency Operating Procedure.",
"EOW": "Engine Overhaul Work.",
"EPA": "Environmental Protection Agency.",
"EPAS": "Electronic Pilot Assistance System.",
"ESN": "Engine Serial Number ",
"ETA": "Estimated Time of Arrival.",
"ETD": "Estimated Time of Departure.",
"ETOPS": "Extended-range Twin-engine Operational Performance Standards. Regulations that allow twin-engine aircraft to fly routes that are further than one hour from a suitable airport.",
"EASA": "European Union Aviation Safety Agency. The aviation regulatory authority for the European Union.",
"EASA Form 1": "An authorized release certificate that accompanies aircraft components after maintenance, overhaul, or repair, certifying that the work was performed to approved standards. Equivalent FAA Form 8130-3.",
"FAA": "Federal Aviation Administration. The US national aviation regulatory authority.",
"FADEC": "Full Authority Digital Engine Control. An electronic system that controls all aspects of engine operation.",
"FAF": "Final Approach Fix.",
"FAR": "Federal Aviation Regulation. Regulations issued by the FAA.",
"FAR Part 121": "Regulations governing scheduled air carriers.",
"FAR Part 135": "Regulations governing on-demand air carriers (charter, air taxi).",
"FBO": "Fixed-Base Operator. A company that provides services to aircraft and pilots at an airport.",
"FCU": "Flight Control Unit.",
"FDR": "Flight Data Recorder.",
"FHA": "Functional Hazard Assessment.",
"Finance Lease (Capital Lease)": "A lease treated as a purchase on the balance sheet.",
"FIS": "Flight Information Service.",
"FL": "Flight Level.",
"FLIR": "Forward Looking InfraRed.",
"FMC": "Flight Management Computer.",
"FMS": "Flight Management System. A computer system that automates many navigation and flight management tasks.",
"FO": "First Officer.",
"FOD": "Foreign Object Debris. Any object that doesn't belong and can cause damage to aircraft or engines. A major concern during maintenance and operations.",
"FPA": "Flight Path Angle.",
"FSE": "Flight Service Engineer.",
"FSI": "Flight Safety International.",
"FSII": "Fuel System Icing Inhibitor.",
"FWD": "Forward.",
"GA": "General Aviation. All aviation activities other than scheduled commercial air transport.",
"GAO": "Government Accountability Office.",
"GARP": "Generally Accepted Recordkeeping Principles.",
"GDP": "Gross Domestic Product.",
"GE": "GE Aerospace (formerly General Electric Aviation). A major manufacturer of aircraft engines and systems.",
"GFC": "Global Financial Crisis.",
"GHG": "Greenhouse Gas.",
"GIC": "Guidance, Interpretation and Clarification.",
"GIS": "Geographic Information System.",
"GMT": "Greenwich Mean Time.",
"GNSS": "Global Navigation Satellite System.",
"GOM": "General Operations Manual.",
"GPU": "Ground Power Unit. A portable power source used to supply electricity to an aircraft while on the ground.",
"GPS": "Global Positioning System. A satellite-based navigation system.",
"GSE": "Ground Support Equipment. Vehicles and equipment used to service aircraft on the ground (e.g., baggage loaders, fuel trucks, pushback tractors).",
"HAL": "Hardware Abstraction Layer.",
"Hard Time (HT)": "A maintenance philosophy where components are overhauled or replaced at fixed intervals, regardless of their condition. Based on time in service.",
"HAT": "Height Above Touchdown.",
"HAZMAT": "Hazardous Materials.",
"HDG": "Heading.",
"HF": "High Frequency.",
"HIRF": "High-Intensity Radiated Fields.",
"Hot Section Inspection (HSI)": "Inspection of the combustion chamber and turbine sections of a jet engine.", 
"HP": "High Pressure.",
"HUD": "Head-Up Display. A transparent display that projects information onto the pilot's forward field of view.",
"HUMS": "Health and Usage Monitoring System. Systems that monitor the condition of aircraft components in real-time.",
"HVAC": "Heating, Ventilation, and Air Conditioning.",
"IAE": "International Aero Engines. A consortium of engine manufacturers.",
"IATA": "International Air Transport Association. A trade association representing the world's airlines.",
"ICAO": "International Civil Aviation Organization. A specialized agency of the United Nations that sets standards and regulations for international aviation.",
"IFR": "Instrument Flight Rules. Regulations governing flight when visibility is limited or when flying in controlled airspace.",
"ILS": "Instrument Landing System. A precision approach system that provides both horizontal and vertical guidance to the runway.",
"IMC": "Instrument Meteorological Conditions. Weather conditions that require pilots to fly under instrument flight rules.",
"IMO": "International Maritime Organization.",
"IMS": "Information Management System.",
"Indemnification": "A contractual agreement to protect someone from financial loss.",
"IPC": "Illustrated Parts Catalog.",
"IR": "Instrument Rating. An endorsement on a pilot certificate that allows the pilot to fly under instrument flight rules.",
"IRAN": "Inspect and Repair As Necessary. Maintenance philosophy.",
"IT": "Information Technology.",
"ITA": "Information Technology Agreement.",
"ITP": "Initial Training Program.",
"IVHM": "Integrated Vehicle Health Management.",
"JAA": "Joint Aviation Authorities (historical, now largely replaced by EASA).",
"JAR": "Joint Aviation Requirements (historical, now largely replaced by EASA regulations).",
"JIT": "Just-in-Time.",
"JOEB": "Joint Operational Evaluation Board.",
"JSA": "Job Safety Analysis.",
"KIAS": "Knots Indicated Airspeed. Airspeed as read directly from the airspeed indicator.",
"KTAS": "Knots True Airspeed. Airspeed corrected for altitude and temperature.",
"LAHSO": "Land and Hold Short Operations.",
"LAME": "Licensed Aircraft Maintenance Engineer.",
"LAN": "Local Area Network.",
"Landing Gears": "Assemblies used for landing the aircraft on ground or maintaining the aircraft in position to move when on ground. Depending on the aircraft type, the aircraft can have wing- installed main landing gears or body-installed main landing gears, nose landing gears, tail landing gears, etc.",
"LCC": "Life Cycle Cost.",
"LCD": "Liquid Crystal Display.",
"LDA": "Localizer-type Directional Aid.",
"Lease": "An agreement allowing the use of an aircraft for a specified period in exchange for rent.",
"LED": "Light Emitting Diode.",
"LEP": "Large Engine Program.",
"Liens": "A legal claim against an aircraft for unpaid debts.",
"Life Limited Part (LLP)": "An aircraft part with a defined lifespan, after which it must be retired from service, regardless of its condition.", 
"Line Replaceable Unit (LRU)": "A modular component designed for quick replacement on the aircraft.",
"LNAV": "Lateral Navigation.",
"LOC": "Localizer.",
"LOE": "Level of Effort.",
"LOFT": "Line-Oriented Flight Training. Simulator training that focuses on realistic scenarios and crew coordination.",
"LOPA": "Layout Of Passenger Accommodations.",
"LP": "Liquid Petroleum.",
"LSA": "Light Sport Aircraft.",
"LTO": "Landing and Take-Off.",
"LV": "Low Visibility.",
"MAA": "Maximum Authorized Altitude.",
"MAC": "Mean Aerodynamic Chord.",
"Magnetic Particle Inspection (MT)": "Uses magnetic fields to detect surface and near-surface cracks in ferromagnetic materials.",
"MAINT": "Maintenance.",
"Maintenance Reserve": "Funds set aside to cover future maintenance costs.",
"Maintenance Steering Group 3 (MSG-3)": "An industry standard process for developing maintenance programs for aircraft.",
"MCT": "Maximum Continuous Thrust.",
"MDA/H": "Minimum Descent Altitude/Height. The lowest altitude or height to which a pilot may descend on a non-precision approach.",
"MEL": "Minimum Equipment List. A list of equipment that can be inoperative on an aircraft and still allow the aircraft to be dispatched for flight.",
"METAR": "Aviation Routine Weather Report. An observation of surface weather conditions at an airport.",
"MFD": "Multi-Function Display.",
"MGTOW": "Maximum Gross Takeoff Weight.",
"MLS": "Microwave Landing System.",
"MMEL": "Master Minimum Equipment List.",
"Mod": "Modification. Changes done according to the SB/SIL.",
"MOC": "Method of Compliance.",
"MPD": "Maintenance Planning Document. Provides guidance on maintenance planning, including task intervals and maintenance requirements.",
"MRO": "Maintenance, Repair, and Overhaul. Companies that provide maintenance services for aircraft.",
"MSL": "Mean Sea Level.",
"MSN": "Manufacturer Serial Number ",
"MTBF": "Mean Time Between Failures.",
"MTBR": "Mean Time Between Removals.",
"MTBUR": "Mean Time Between Unscheduled Removals.",
"MTOW": "Maximum Takeoff Weight.",
"N1/N2": "Rotational speeds of compressor and turbine spools in a turbofan engine.",
"NAA": "National Aviation Authority (e.g., FAA, EASA).",
"NAV": "Navigation.",
"NAVAID": "Navigational Aid.",
"NDB": "Non-Directional Beacon. A radio transmitter used as a navigational aid.",
"NDT/NDI": "Non-Destructive Testing/Inspection. A range of techniques used to evaluate the properties of a material, component or system without causing damage.", 
"NOTAM": "Notice to Air Missions. A notice containing information concerning temporary or potentially hazardous conditions.",
"NPA": "Notice of Proposed Amendment.",
"NPI": "New Product Introduction.",
"NPRM": "Notice of Proposed Rulemaking.",
"NTSB": "National Transportation Safety Board. The US government agency responsible for investigating transportation accidents.",
"O&M": "Operations and Maintenance.",
"OAT": "Outside Air Temperature.",
"OC = On Condition": "A maintenance philosophy where components are inspected periodically and replaced or overhauled only when they fail to meet specific condition standards. No fixed life but are subject to inspection.",
"OEM": "Original Equipment Manufacturer.",
"OH (or OVH)": "Overhauled. A component that has been disassembled, inspected, repaired, and reassembled to like-new condition.",
"OJT": "On-the-Job Training.",
"On Condition (OC)": "A maintenance philosophy where components are inspected periodically and replaced or overhauled only when they fail to meet specific condition standards. No fixed life but are subject to inspection.",
"Operating Lease": "A lease treated as an operating expense.",
"Opex": "Operating Expenditure. Ongoing costs to operate an airline or aviation business.",
"Ops Specs": "Operations Specifications.",
"Original Equipment Manufacturer (OEM)": "A company that manufactures products that other companies then market or incorporate into their own products.",
"OVC": "Overcast.",
"PA": "Public Address.",
"PAX": "Passengers.",
"PAPI": "Precision Approach Path Indicator.",
"Part 121": "FAA regulations governing scheduled air carriers.",
"Part 135": "FAA regulations governing on-demand air carriers (charter, air taxi).",
"PIC": "Pilot in Command.",
"PIN": "Part Identification Number.",
"PIREP": "Pilot Report. A report of weather conditions encountered in flight.",
"PMA": "Parts Manufacturer Approval. An FAA approval for a company to manufacture replacement parts for aircraft.",
"PMI": "Positive Material Identification.",
"POH": "Pilot's Operating Handbook.",
"PPE": "Personal Protective Equipment.",
"Predictive Maintenance": "Using data analysis and condition monitoring to predict when maintenance will be needed.", 
"Preventive Maintenance": "Scheduled maintenance performed to prevent failures and maintain system reliability.",
"psi": "pounds per square inch.",
"PTT": "Push-To-Talk.",
"QAR": "Quality Assurance Review.",
"QFE": "Atmospheric pressure at field elevation.",
"QMS": "Quality Management System.",
"QNE": "Standard altimeter setting of 29.92 inches of mercury (1013.25 hPa).",
"QNH": "Altimeter setting to read altitude above mean sea level.",
"QRA": "Quantitative Risk Assessment.",
"QRH": "Quick Reference Handbook.",
"Radiographic Testing (RT)": "Uses X-rays or gamma rays to inspect internal structures.",
"RAM": "Random Access Memory.",
"R&D": "Research and Development.",
"RANS": "Reynolds-Averaged Navier-Stokes.",
"RAPCON": "Radar Approach Control.",
"RASS": "Remote Airport Surveillance System.",
"RCM": "Reliability-Centered Maintenance. A maintenance strategy that focuses on identifying the most critical functions of a system and developing maintenance tasks to ensure those functions are maintained.",
"RDO": "Required Date of Operation.",
"Rejected Takeoff (RTO)": "Aborting the takeoff run.",
"Reliability-Centered Maintenance (RCM)": "A maintenance strategy that focuses on identifying the most critical functions of a system and developing maintenance tasks to ensure those functions are maintained.",
"Removal and Installation (R/I)": "The process of removing and installing a component.",
"Request for Information (RFI)": "A document used to gather information from potential suppliers.",
"Request for Proposal (RFP)": "A document used to solicit proposals from potential suppliers.",
"Residual Value": "The estimated value of an aircraft at the end of a lease term.",
"RF": "Radio Frequency.",
"RNAV": "Area Navigation.",
"ROI": "Return on Investment.",
"ROM": "Read-Only Memory.",
"RPA": "Remotely Piloted Aircraft.",
"RPM": "Revolutions Per Minute.",
"RPT": "Regular Public Transport.",
"Residual Value": "The estimated value of an aircraft at the end of a lease term.",
"SAE": "Society of Automotive Engineers.",
"SAR": "Search and Rescue.",
"SB": "Service Bulletin. A notification from an aircraft or engine manufacturer recommending maintenance or modifications.",
"Securitization": "Bundling aircraft lease payments into securities for sale to investors.",
"SELCAL": "Selective Calling.",
"SEP": "Single Engine Piston.",
"Serviceable (SV)": "A component that is in good working order and meets all applicable standards.",
"Shop Replaceable Unit (SRU)": "A component that is repaired or replaced in a maintenance shop.",
"SID": "Standard Instrument Departure. A published procedure for departing an airport under IFR.",
"SIL": "Service Information Letter. The same purpose as SB but the operator will need to decide whether to comply or not.",
"SLS": "Sidelobe Suppression.",
"SMOH": "Since Major Overhaul.",
"SOP": "Standard Operating Procedure.",
"SOW": "Scope of Work.",
"SP": "Service Provider.",
"SPA": "Single Pilot Aircraft.",
"SPE": "Single Point Earth.",
"SPI": "Serial Peripheral Interface.",
"SQA": "Software Quality Assurance.",
"SRM": "Safety Risk Management.",
"STAR": "Standard Terminal Arrival Route. A published procedure for arriving at an airport under IFR.",
"STC": "Supplemental Type Certificate. An FAA approval for a modification to an existing type certificate.",
"STOL": "Short Takeoff and Landing.",
"SWOT": "Strengths, Weaknesses, Opportunities, Threats.", 
"SWR": "Standing Wave Ratio.",
"TAA": "Technically Advanced Aircraft.",
"TACAN": "Tactical Air Navigation System.",
"TAF": "Terminal Aerodrome Forecast. A forecast of weather conditions at an airport.",
"TAS": "True Airspeed.",
"TBO": "Time Between Overhauls. The recommended interval for overhauling an engine.",
"TC": "Type Certificate. An FAA approval for a new aircraft, engine, or propeller design.",
"TCAS": "Traffic Collision Avoidance System. An airborne system that alerts pilots to potential collisions with other aircraft.",
"TCDS": "Type Certificate Data Sheet. A document that lists the specifications and limitations for a type-certificated aircraft, engine, or propeller.",
"TFR": "Temporary Flight Restriction.",
"THS": "Tail Horizontal Stabilizer.",
"TIS": "Traffic Information Service.",
"TMA": "Terminal Maneuvering Area.",
"Troubleshooting": "The process of diagnosing and resolving aircraft system faults.",
"TSA": "Transportation Security Administration.", 
"TSI": "Time Since Installation. The time a component has been in service since it was last installed on an aircraft.", 
"TSO": "Technical Standard Order. A minimum performance standard for specified materials, parts, and appliances used on civil aircraft. Also, Time Since Overhaul.",
"TSN": "Time Since New. The total time a component has been in service since it was manufactured.",
"TWR": "Tower.",
"UAS": "Unmanned Aircraft System (Drone).",
"UAV": "Unmanned Aerial Vehicle (Drone).",
"UCAV": "Unmanned Combat Aerial Vehicle.",
"UHF": "Ultra High Frequency.",
"UL": "Underwriters Laboratories.",
"Ultrasonic Testing (UT)": "Uses sound waves to detect internal flaws.", 
"ULV": "Ultra Low Volume.", 
"Unserviceable (US)": "A component that is not in good working order and does not meet applicable standards.", 
"UPS": "Uninterruptible Power Supply.", 
"URL": "Uniform Resource Locator.", 
"USB": "Universal Serial Bus.", 
"UTC": "Coordinated Universal Time (formerly Greenwich Mean Time).", 
"V1": "Takeoff decision speed.", 
"V2": "Takeoff safety speed.", 
"VA": "Design maneuvering speed.", 
"VFR": "Visual Flight Rules. Regulations governing flight when visibility is good enough to fly by visual reference to the ground.", 
"VHF": "Very High Frequency.", 
"Visual Inspection (VT)": "A basic inspection using the naked eye or magnifying tools.", 
"VMC": "Visual Meteorological Conditions. Weather conditions that allow pilots to fly under visual flight rules.", 
"VOR": "VHF Omnidirectional Range. A radio navigation aid that provides bearing information to an aircraft.",
"VORTAC": "VOR combined with TACAN.",
"VR": "Rotation speed.",
"VS": "Stalling Speed.",
"VSO": "Stalling speed in landing configuration.",
"VTOL": "Vertical Takeoff and Landing.", 
"WAN": "Wide Area Network.",
"WEF": "With Effect From.",
"Wet Lease": "(See ACMI).",
"WIP": "Work in Progress.",
"WOC": "Without Compensation.",
"W/O": "Without.", 
"XML": "Extensible Markup Language.",
"YOY": "Year-Over-Year.",
"ZFW": "Zero Fuel Weight. The weight of the aircraft without fuel.",
"Zone Inspection": "Scheduled inspection of a specific area of an aircraft for damage or wear.",
"Zulu Time": "Another term for Coordinated Universal Time (UTC)."

}